version: "3.9"

services:
  wandynamics-demo01:
    build: .
    image: "wandynamics-demo01:latest"
    container_name: wandynamics-demo01
    restart: no
    command: ['tail', '-f', '/dev/null']
    network_mode: "host"

    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
      - LC_ALL=C
    volumes:
      - ../:/workspace