version: "3.9"

services:
  pdt-dev04:
    build: .
    image: "pdt-dev04:latest"
    container_name: pdt-dev04
    restart: no
    command: ['tail', '-f', '/dev/null']
    network_mode: "host"

    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
      - LC_ALL=C
    volumes:
      - ../:/workspace